postgres:
  database: test_workplace
  user: test_workplace_user
  password: karpovich
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5

redis:
  host: localhost
  port: 6379

host: 127.0.0.1
port: 8081
